client gateway_reyee {
    # Permite conexiones desde cualquier IP de la red local
    ipaddr = 0.0.0.0/0
    
    # ESTE ES EL SECRETO QUE DEBES PONER EN RUIJIE CLOUD
    secret = IEQ_Radius_Secret_2026
}
